/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <pthread.h>
#include <unistd.h>
#include <stdlib.h>
#include <time.h>
#include "bakery.h"


void
bakery_prog_1(char *host)
{
	CLIENT *clnt;
	struct BAKERY  *result_1;
	struct BAKERY  bakery_proc_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, BAKERY_PROG, BAKERY_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	srand(time(NULL));
	int interval = rand() % 3 + 1;
	sleep(interval);
	bakery_proc_1_arg.pid = getpid();
	bakery_proc_1_arg.op = GET_NUMBER;
	result_1 = bakery_proc_1(&bakery_proc_1_arg, clnt);
	if (result_1 == (struct BAKERY *) NULL) {
		clnt_perror(clnt, "call failed");
	}
	printf("%d client №%d (sleep %d)\n", result_1->pid, result_1->num, interval);
	srand(time(NULL));
	interval = rand() % 3 + 2;
	sleep(interval);
	bakery_proc_1_arg.op = ENTER_CRIT_SECTION; 
	bakery_proc_1_arg.num = result_1->op;
	bakery_proc_1_arg.pid = getpid();
	result_1 = bakery_proc_1(&bakery_proc_1_arg, clnt);
	if (result_1 == (struct BAKERY *) NULL) {
		clnt_perror(clnt, "call failed");
	}
	printf("%d client writes %c (sleep %d)\n", result_1->pid, result_1->result, interval);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	bakery_prog_1 (host);
exit (0);
}
